### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EdouardBoute** [CERES-Sorbonne/Panoptic#12]
**STEP YOU MEET THE BUG**
at use

**Describe the bug**
Soucis d'affichage : si le titre du projet est trop long, le bouton pour retourner sur la page de choix des projets disparaît.

**To Reproduce**
Le titre en question : "Images_Presentation_Publique"

**Expected behavior**
Que le bouton apparaisse malgré la longueur du titre 

**Screenshots**
![Capture d’écran 2024-09-03 163110](https://github.com/user-attachments/assets/f27653ed-596a-42f0-b9eb-8cce48fb10d6)

**Device**
 - OS: MacOS
 - Python Version: 3.11.9

**Comment by godicked** [comment]
Is fixed in the next release
